// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Google.SignIn;

namespace AppInviteSample
{
	public partial class SignInViewController : UIViewController, ISignInDelegate, ISignInUIDelegate
	{
		public SignInViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidAppear (bool animated)
		{
			base.ViewDidAppear (animated);

			bgText.Text = "App Invites\niOS demo";

			// Sign the user in automatically
			SignIn.SharedInstance.UIDelegate = this;
			SignIn.SharedInstance.SignInUserSilently ();

			// TODO(developer) Configure the sign-in button look/feel
			SignIn.SharedInstance.Delegate = this;
		}

		public void DidSignIn (SignIn signIn, GoogleUser user, NSError error)
		{
			if (error == null) {
				PerformSegue ("SignedInScreen", this);
			} else {
				// Something went wrong; for example, the user could haved clicked cancel.
			}
		}

		override public UIStatusBarStyle PreferredStatusBarStyle ()
		{
			return UIStatusBarStyle.LightContent;
		}

		partial void UnwindToSignIn (UIKit.UIStoryboardSegue sender)
		{
			SignIn.SharedInstance.Delegate = this;
		}
	}
}
