using System;
using System.Collections.Generic;

using Foundation;
using ObjCRuntime;
using UserNotifications;

namespace Firebase.CloudMessaging
{
	// typedef void(^FIRMessagingFCMTokenFetchCompletion)(NSString * _Nullable FCMToken, NSError* _Nullable error) FIR_SWIFT_NAME(MessagingFCMTokenFetchCompletion);
	delegate void MessagingFcmTokenFetchCompletionHandler ([NullAllowed] string fcmToken, [NullAllowed] NSError error);

	// typedef void(^FIRMessagingDeleteFCMTokenCompletion)(NSError * _Nullable error) FIR_SWIFT_NAME(MessagingDeleteFCMTokenCompletion);
	delegate void MessagingDeleteFcmTokenCompletionHandler ([NullAllowed] NSError error);

	// typedef void (^FIRMessagingTopicOperationCompletion)(NSError *_Nullable error);
	delegate void MessagingTopicOperationCompletionHandler ([NullAllowed] NSError error);

	// @interface FIRMessagingMessageInfo : NSObject
	[BaseType (typeof (NSObject), Name = "FIRMessagingMessageInfo")]
	interface MessageInfo
	{
		// @property (readonly, assign, nonatomic) FIRMessagingMessageStatus status;
		[Export ("status", ArgumentSemantic.Assign)]
		MessageStatus Status { get; }
	}

	// @interface FIRMessagingRemoteMessage : NSObject
	[DisableDefaultCtor]
	[BaseType (typeof (NSObject), Name = "FIRMessagingRemoteMessage")]
	interface RemoteMessage
	{
		// @property (readonly, copy, nonatomic) NSString * _Nonnull messageID;
		[Export ("messageID")]
		string MessageId { get; }

		// @property(nonatomic, readonly, strong, nonnull) NSDictionary *appData;
		[Export ("appData", ArgumentSemantic.Strong)]
		NSDictionary AppData { get; }
	}

	interface IMessagingDelegate
	{
	}

	// @protocol FIRMessagingDelegate <NSObject>
	[Model (AutoGeneratedName = true)]
	[Protocol]
	[BaseType (typeof (NSObject), Name = "FIRMessagingDelegate")]
	interface MessagingDelegate
	{
		// @optional -(void)messaging:(FIRMessaging * _Nonnull)messaging didReceiveRegistrationToken:(NSString * _Nonnull)fcmToken;
		[Export ("messaging:didReceiveRegistrationToken:")]
		void DidReceiveRegistrationToken (Messaging messaging, string fcmToken);

		// - (void)messaging:(nonnull FIRMessaging *)messaging didReceiveMessage:(nonnull FIRMessagingRemoteMessage *)remoteMessage FIR_SWIFT_NAME(messaging(_:didReceive:)
		[Obsolete ("FCM direct channel is deprecated, please use APNs for downstream message handling.")]
		[Export ("messaging:didReceiveMessage:")]
		void DidReceiveMessage (Messaging messaging, RemoteMessage remoteMessage);
	}

	// @interface FIRMessaging : NSObject
	[DisableDefaultCtor]
	[BaseType (typeof (NSObject), Name = "FIRMessaging")]
	interface Messaging
	{
		// extern NSString *const _Nonnull FIRMessagingSendSuccessNotification;
		[Obsolete]
		[Notification]
		[Field ("FIRMessagingSendSuccessNotification", "__Internal")]
		NSString SendSuccessNotification { get; }

		// extern NSString *const _Nonnull FIRMessagingSendErrorNotification;
		[Obsolete]
		[Notification]
		[Field ("FIRMessagingSendErrorNotification", "__Internal")]
		NSString SendErrorNotification { get; }

		// extern NSString *const _Nonnull FIRMessagingMessagesDeletedNotification;
		[Obsolete]
		[Notification]
		[Field ("FIRMessagingMessagesDeletedNotification", "__Internal")]
		NSString MessagesDeletedNotification { get; }

		// extern NSString *const _Nonnull FIRMessagingConnectionStateChangedNotification;
		[Obsolete]
		[Notification]
		[Field ("FIRMessagingConnectionStateChangedNotification", "__Internal")]
		NSString ConnectionStateChangedNotification { get; }

		// extern NSString *const _Nonnull FIRMessagingRegistrationTokenRefreshedNotification;
		[Obsolete]
		[Notification]
		[Field ("FIRMessagingRegistrationTokenRefreshedNotification", "__Internal")]
		NSString RegistrationTokenRefreshedNotification { get; }

		// @property(nonatomic, weak, nullable) id<FIRMessagingDelegate> delegate;
		[NullAllowed]
		[Export ("delegate", ArgumentSemantic.Weak)]
		IMessagingDelegate Delegate { get; set; }

		// @property(nonatomic) BOOL shouldEstablishDirectChannel;
		[Obsolete ("FCM direct channel is deprecated, please use APNs channel for downstream message delivery.")]
		[Export ("shouldEstablishDirectChannel")]
		bool ShouldEstablishDirectChannel { get; set; }

		// @property(nonatomic, readonly) BOOL isDirectChannelEstablished;
		[Obsolete ("FCM direct channel is deprecated, please use APNs channel for downstream message delivery.")]
		[Export ("isDirectChannelEstablished")]
		bool IsDirectChannelEstablished { get; }

		// +(instancetype _Nonnull)messaging;
		[Static]
		[Export ("messaging")]
		Messaging SharedInstance { get; }

		// +(FIRMessagingExtensionHelper * _Nonnull)extensionHelper __attribute__((swift_name("serviceExtension()"))) __attribute__((availability(ios, introduced=10.0)));
		[Introduced (PlatformName.iOS, 10, 0, 0)]
		[Static]
		[Export ("extensionHelper")]
		MessagingExtensionHelper ExtensionHelper { get; }

		// @property(nonatomic, copy, nullable) NSData *APNSToken FIR_SWIFT_NAME(apnsToken);
		[NullAllowed]
		[Export ("APNSToken", ArgumentSemantic.Copy)]
		NSData ApnsToken { get; set; }

		// - (void)setAPNSToken:(nonnull NSData *)apnsToken type:(FIRMessagingAPNSTokenType)type;
		[Export ("setAPNSToken:type:")]
		void SetApnsToken (NSData apnsToken, ApnsTokenType type);

		// @property(nonatomic, assign, getter=isAutoInitEnabled) BOOL autoInitEnabled;
		[Export ("autoInitEnabled")]
		bool AutoInitEnabled { [Bind ("isAutoInitEnabled")] get; set; }

		// @property(nonatomic, readonly, nullable) NSString *FCMToken FIR_SWIFT_NAME(fcmToken);
		[NullAllowed]
		[Export ("FCMToken")]
		string FcmToken { get; }

		// - (void)retrieveFCMTokenForSenderID:(nonnull NSString *)senderID completion:(nonnull FIRMessagingFCMTokenFetchCompletion) completion FIR_SWIFT_NAME(retrieveFCMToken(forSenderID:completion:));
		[Async]
		[Export ("retrieveFCMTokenForSenderID:completion:")]
		void RetrieveFcmToken (string senderId, MessagingFcmTokenFetchCompletionHandler completion);

		// - (void)deleteFCMTokenForSenderID:(nonnull NSString *)senderID completion:(nonnull FIRMessagingDeleteFCMTokenCompletion) completion FIR_SWIFT_NAME(deleteFCMToken(forSenderID:completion:));
		[Async]
		[Export ("deleteFCMTokenForSenderID:completion:")]
		void DeleteFcmToken (string senderId, MessagingDeleteFcmTokenCompletionHandler completion);

		// -(void)subscribeToTopic:(NSString * _Nonnull)topic;
		[Export ("subscribeToTopic:")]
		void Subscribe (string topic);

		// -(void)subscribeToTopic:(NSString * _Nonnull)topic completion:(nullable FIRMessagingTopicOperationCompletion)completion;
		[Async]
		[Export ("subscribeToTopic:completion:")]
		void Subscribe (string topic, MessagingTopicOperationCompletionHandler completion);

		// -(void)unsubscribeFromTopic:(NSString * _Nonnull)topic;
		[Export ("unsubscribeFromTopic:")]
		void Unsubscribe (string topic);

		//-(void)unsubscribeFromTopic:(NSString * _Nonnull)topic completion:(nullable FIRMessagingTopicOperationCompletion)completion;
		[Async]
		[Export ("unsubscribeFromTopic:completion:")]
		void Unsubscribe (string topic, MessagingTopicOperationCompletionHandler completion);

		// -(void)sendMessage:(NSDictionary * _Nonnull)message to:(NSString * _Nonnull)receiver withMessageID:(NSString * _Nonnull)messageID timeToLive:(int64_t)ttl;
		[Obsolete ("Upstream messaging through direct channel is deprecated. For realtime updates, use Cloud Firestore, Realtime Database, or other services.")]
		[Export ("sendMessage:to:withMessageID:timeToLive:")]
		void SendMessage (NSDictionary nsMessage, string receiver, string messageId, long ttl);

		[Obsolete ("Upstream messaging through direct channel is deprecated. For realtime updates, use Cloud Firestore, Realtime Database, or other services.")]
		[Wrap ("SendMessage (message == null ? null : NSDictionary.FromObjectsAndKeys (System.Linq.Enumerable.ToArray (message.Values), System.Linq.Enumerable.ToArray (message.Keys), message.Keys.Count), receiver, messageId, ttl)")]
		void SendMessage (Dictionary<object, object> message, string receiver, string messageId, long ttl);

		// -(FIRMessagingMessageInfo * _Nonnull)appDidReceiveMessage:(NSDictionary * _Nonnull)message;
		[Export ("appDidReceiveMessage:")]
		MessageInfo AppDidReceiveMessage (NSDictionary message);
	}

	// @interface FIRMessagingExtensionHelper : NSObject
	[Introduced (PlatformName.iOS, 10, 0, 0)]
	[BaseType (typeof (NSObject), Name = "FIRMessagingExtensionHelper")]
	interface MessagingExtensionHelper {
		// -(void)populateNotificationContent:(UNMutableNotificationContent * _Nonnull)content withContentHandler:(void (^ _Nonnull)(UNNotificationContent * _Nonnull))contentHandler;
		[Export ("populateNotificationContent:withContentHandler:")]
		void PopulateNotificationContent (UNMutableNotificationContent content, Action<UNNotificationContent> contentHandler);
	}
}
